sudo: required
services: 
    - docker

before_install:
    - docker build -t kamransadique/docker-test -f Dockerfile.dev .

script:
    - docker run -e CI=true kamransadique/docker-test npm run test

deploy:
    edge: true
    provider: elasticbeanstalk
    region: "us-east-2"
    app: "docker-test"
    env: "DockerTest-env"
    bucket_name: $BUCKET_NAME
    bucket_path: "docker-test"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY