sudo: required
services: 
    - docker

before_install:
    - docker build -t kamransadique/docker-test -f Dockerfile.dev .

script:
    - docker run kamransadique/docker-test npm run test -- --coverage